// Component Styles
export const styles = {
    appContainer: {
        display: 'flex',
        minHeight: '100vh',
    },
    sidebar: {
        width: '260px',
        background: 'rgba(255, 255, 255, 0.98)',
        backdropFilter: 'blur(10px)',
        padding: '30px 20px',
        boxShadow: '4px 0 20px rgba(0, 0, 0, 0.1)',
        position: 'fixed',
        height: '100vh',
        overflowY: 'auto',
        animation: 'slideIn 0.5s ease',
        display: 'flex',
        flexDirection: 'column',
    },
    logo: {
        fontSize: '26px',
        fontWeight: '800',
        color: '#667eea',
        marginBottom: '40px',
        letterSpacing: '-0.5px',
    },
    navItem: {
        width: '100%',
        padding: '14px 18px',
        background: 'transparent',
        color: '#555',
        border: 'none',
        borderRadius: '10px',
        marginBottom: '8px',
        cursor: 'pointer',
        fontSize: '15px',
        fontWeight: '600',
        textAlign: 'left',
        transition: 'all 0.2s ease',
        display: 'block',
    },
    navItemActive: {
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        color: 'white',
    },
    logoutButton: {
        marginTop: 'auto',
        background: '#f5576c',
        color: 'white',
    },
    mainContent: {
        flex: 1,
        marginLeft: '260px',
        padding: '40px',
        animation: 'fadeIn 0.6s ease',
    },

    pageHeader: {
        background: 'white',
        borderRadius: '16px',
        padding: '28px',
        marginBottom: '24px',
        boxShadow: '0 4px 20px rgba(0, 0, 0, 0.08)',
    },
    headerFlex: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: '16px',
    },
    pageTitle: {
        fontSize: '28px',
        fontWeight: '700',
        color: '#333',
        marginBottom: '6px',
    },
    pageSubtitle: {
        color: '#666',
        fontSize: '15px',
    },
    card: {
        background: 'white',
        borderRadius: '16px',
        padding: '28px',
        marginBottom: '20px',
        boxShadow: '0 4px 20px rgba(0, 0, 0, 0.06)',
    },
    cardTitle: {
        marginBottom: '20px',
        color: '#333',
        fontSize: '18px',
        fontWeight: '600',
    },
    button: {
        padding: '12px 24px',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        color: 'white',
        border: 'none',
        borderRadius: '10px',
        fontSize: '15px',
        fontWeight: '600',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
    },
    deleteButton: {
        background: '#f5576c',
        marginTop: '10px',
    },
    smallButton: {
        padding: '8px 16px',
        fontSize: '13px',
    },
    input: {
        width: '100%',
        padding: '14px 16px',
        border: '2px solid #e8e8e8',
        borderRadius: '10px',
        fontSize: '15px',
        marginBottom: '14px',
        transition: 'all 0.2s ease',
        fontFamily: 'inherit',
        outline: 'none',
    },
    textarea: {
        width: '100%',
        padding: '14px 16px',
        border: '2px solid #e8e8e8',
        borderRadius: '10px',
        fontSize: '15px',
        marginBottom: '14px',
        minHeight: '120px',
        fontFamily: 'inherit',
        resize: 'vertical',
        outline: 'none',
    },
    grid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
        gap: '20px',
        marginTop: '20px',
    },
    statCard: {
        borderRadius: '16px',
        padding: '28px',
        color: 'white',
        boxShadow: '0 8px 24px rgba(0, 0, 0, 0.12)',
    },
    statValue: {
        fontSize: '42px',
        fontWeight: '700',
        marginBottom: '8px',
    },
    statLabel: {
        fontSize: '16px',
        opacity: 0.9,
        fontWeight: '500',
    },
    bookItem: {
        background: 'white',
        borderRadius: '16px',
        padding: '24px',
        boxShadow: '0 4px 16px rgba(0, 0, 0, 0.06)',
        transition: 'all 0.2s ease',
        cursor: 'pointer',
    },
    bookCover: {
        width: '100%',
        height: '120px',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        borderRadius: '12px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: '16px',
    },
    bookCoverText: {
        fontSize: '48px',
        fontWeight: '700',
        color: 'white',
        opacity: 0.8,
    },
    bookTitle: {
        color: '#333',
        fontSize: '18px',
        fontWeight: '600',
        marginBottom: '6px',
    },
    bookAuthor: {
        color: '#666',
        fontSize: '14px',
        marginBottom: '12px',
    },
    badgeContainer: {
        display: 'flex',
        gap: '8px',
        marginBottom: '12px',
        flexWrap: 'wrap',
    },
    badge: {
        display: 'inline-block',
        padding: '4px 12px',
        background: 'rgba(102, 126, 234, 0.1)',
        color: '#667eea',
        borderRadius: '20px',
        fontSize: '13px',
        fontWeight: '600',
    },
    bookDate: {
        fontSize: '12px',
        color: '#999',
        marginBottom: '12px',
    },
    emptyState: {
        textAlign: 'center',
        fontSize: '16px',
        color: '#666',
        padding: '40px 20px',
    },
    errorMessage: {
        background: '#fff5f5',
        color: '#e53e3e',
        padding: '12px 16px',
        borderRadius: '8px',
        marginBottom: '16px',
        fontSize: '14px',
    },

    // Reader styles
    readerContainer: {
        display: 'flex',
        flexDirection: 'column',
        height: '100vh',
        background: '#f8f9fa',
    },
    readerHeader: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '16px 24px',
        background: 'white',
        borderBottom: '1px solid #e8e8e8',
        boxShadow: '0 2px 8px rgba(0, 0, 0, 0.04)',
    },
    readerBackButton: {
        padding: '10px 20px',
        background: '#f0f0f0',
        color: '#333',
        border: 'none',
        borderRadius: '8px',
        fontSize: '14px',
        fontWeight: '600',
        cursor: 'pointer',
    },
    readerBookInfo: {
        textAlign: 'center',
    },
    readerTitle: {
        fontSize: '18px',
        fontWeight: '600',
        color: '#333',
        marginBottom: '4px',
    },
    readerAuthor: {
        fontSize: '14px',
        color: '#666',
    },
    pageIndicator: {
        padding: '8px 16px',
        background: '#f0f0f0',
        borderRadius: '8px',
        fontSize: '14px',
        fontWeight: '500',
        cursor: 'pointer',
    },
    jumpForm: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    jumpInput: {
        width: '60px',
        padding: '4px 8px',
        border: '2px solid #667eea',
        borderRadius: '6px',
        fontSize: '14px',
        textAlign: 'center',
        outline: 'none',
    },
    pageTotal: {
        color: '#666',
    },
    headerControls: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    displayModeButton: {
        padding: '8px 16px',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        color: 'white',
        border: 'none',
        borderRadius: '8px',
        fontSize: '13px',
        fontWeight: '600',
        cursor: 'pointer',
    },
    readerMain: {
        flex: 1,
        display: 'flex',
        position: 'relative',
        overflow: 'hidden',
    },
    readerContent: {
        flex: 1,
        padding: '40px 80px',
        overflowY: 'auto',
        background: 'white',
        margin: '20px',
        marginRight: '60px',
        borderRadius: '12px',
        boxShadow: '0 2px 12px rgba(0, 0, 0, 0.06)',
    },
    readerContentClean: {
        flex: 1,
        padding: '40px 80px',
        overflowY: 'auto',
        background: 'white',
        margin: '20px',
        borderRadius: '12px',
        boxShadow: '0 2px 12px rgba(0, 0, 0, 0.06)',
    },
    scrollPageContainer: {
        marginBottom: '40px',
        paddingBottom: '40px',
        borderBottom: '2px dashed #e8e8e8',
    },
    readerPageLabel: {
        fontSize: '14px',
        color: '#999',
        fontWeight: '600',
        marginBottom: '20px',
        padding: '8px 16px',
        background: '#f8f9fa',
        borderRadius: '8px',
        display: 'inline-block',
    },
    readerLoading: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100%',
        color: '#666',
        fontSize: '16px',
    },
    readerText: {
        fontSize: '18px',
        lineHeight: '1.8',
        color: '#333',
        maxWidth: '800px',
        margin: '0 auto',
        whiteSpace: 'pre-wrap',
        wordWrap: 'break-word',
    },
    paragraph: {
        marginBottom: '16px',
        textAlign: 'justify',
    },
    customScrollbar: {
        position: 'absolute',
        right: '20px',
        top: '20px',
        bottom: '20px',
        width: '24px',
        background: '#e8e8e8',
        borderRadius: '12px',
        cursor: 'pointer',
    },
    scrollbarTrack: {
        position: 'absolute',
        top: '0',
        bottom: '0',
        left: '50%',
        transform: 'translateX(-50%)',
        width: '4px',
        background: '#d0d0d0',
        borderRadius: '2px',
    },
    scrollbarThumb: {
        position: 'absolute',
        left: '50%',
        transform: 'translate(-50%, -50%)',
        width: '20px',
        height: '40px',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        borderRadius: '10px',
        boxShadow: '0 2px 8px rgba(102, 126, 234, 0.4)',
    },
    translationPopup: {
        position: 'fixed',
        background: 'white',
        borderRadius: '12px',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.15)',
        padding: '16px',
        minWidth: '280px',
        maxWidth: '360px',
        zIndex: 1000,
        animation: 'fadeIn 0.2s ease',
    },
    translationHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '12px',
        paddingBottom: '12px',
        borderBottom: '1px solid #e8e8e8',
    },
    translationWord: {
        fontSize: '18px',
        fontWeight: '600',
        color: '#333',
    },
    translationClose: {
        background: 'none',
        border: 'none',
        fontSize: '18px',
        color: '#999',
        cursor: 'pointer',
        padding: '4px 8px',
    },
    translationBody: {
        marginBottom: '12px',
    },
    translatingText: {
        color: '#999',
        fontStyle: 'italic',
    },
    translationResult: {
        fontSize: '20px',
        fontWeight: '600',
        color: '#667eea',
    },
    translationContext: {
        fontSize: '13px',
        color: '#666',
        fontStyle: 'italic',
        padding: '10px',
        background: '#f8f9fa',
        borderRadius: '8px',
        marginBottom: '12px',
        lineHeight: '1.5',
    },
    translationActions: {
        display: 'flex',
        justifyContent: 'flex-end',
    },
    saveWordButton: {
        padding: '10px 20px',
        background: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
        color: 'white',
        border: 'none',
        borderRadius: '8px',
        fontSize: '14px',
        fontWeight: '600',
        cursor: 'pointer',
    },
    readerFooter: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '24px',
        padding: '16px 24px',
        background: 'white',
        borderTop: '1px solid #e8e8e8',
    },
    navButton: {
        padding: '12px 28px',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        color: 'white',
        border: 'none',
        borderRadius: '10px',
        fontSize: '15px',
        fontWeight: '600',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
    },
    progressBar: {
        flex: 1,
        maxWidth: '400px',
        height: '8px',
        background: '#e8e8e8',
        borderRadius: '4px',
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        borderRadius: '4px',
        transition: 'width 0.3s ease',
    },

    // Dictionary styles
    wordGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
        gap: '20px',
        marginTop: '20px',
    },
    dictionaryCard: {
        background: 'white',
        borderRadius: '16px',
        padding: '24px',
        boxShadow: '0 4px 16px rgba(0, 0, 0, 0.06)',
    },
    wordHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: '8px',
    },
    wordTitle: {
        fontSize: '20px',
        fontWeight: '700',
        color: '#333',
    },
    wordLang: {
        fontSize: '12px',
        color: '#999',
        background: '#f0f0f0',
        padding: '4px 8px',
        borderRadius: '4px',
    },
    wordTranslation: {
        fontSize: '18px',
        color: '#667eea',
        fontWeight: '600',
        marginBottom: '12px',
    },
    wordContextBox: {
        background: '#f8f9fa',
        padding: '12px',
        borderRadius: '8px',
        marginBottom: '12px',
    },
    contextLabel: {
        fontSize: '12px',
        color: '#999',
        fontWeight: '600',
        display: 'block',
        marginBottom: '4px',
    },
    wordContext: {
        fontSize: '14px',
        color: '#555',
        fontStyle: 'italic',
        lineHeight: '1.5',
    },
    wordBookInfo: {
        fontSize: '13px',
        color: '#666',
        marginBottom: '8px',
    },
    wordDate: {
        fontSize: '12px',
        color: '#999',
        marginBottom: '12px',
    },
    wordActions: {
        display: 'flex',
        gap: '10px',
        flexWrap: 'wrap',
    },
    createFlashcardButton: {
        padding: '8px 16px',
        background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        color: 'white',
        border: 'none',
        borderRadius: '8px',
        fontSize: '13px',
        fontWeight: '600',
        cursor: 'pointer',
    },
    filterRow: {
        display: 'flex',
        gap: '16px',
        flexWrap: 'wrap',
    },
    filterInput: {
        flex: 1,
        minWidth: '200px',
        marginBottom: '0',
    },
    filterSelect: {
        minWidth: '180px',
        marginBottom: '0',
        cursor: 'pointer',
    },

    // Flashcard styles
    flashcardMenu: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
        gap: '24px',
        marginTop: '20px',
    },
    menuCard: {
        background: 'white',
        borderRadius: '20px',
        padding: '32px',
        textAlign: 'center',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        boxShadow: '0 4px 20px rgba(0, 0, 0, 0.06)',
    },
    reviewCard: {
        borderLeft: '4px solid #f5576c',
    },
    allCardsCard: {
        borderLeft: '4px solid #667eea',
    },
    createCard: {
        borderLeft: '4px solid #43e97b',
    },
    menuCardIcon: {
        marginBottom: '16px',
    },
    dueCount: {
        display: 'inline-block',
        width: '56px',
        height: '56px',
        lineHeight: '56px',
        background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
        color: 'white',
        borderRadius: '50%',
        fontSize: '24px',
        fontWeight: '700',
    },
    totalCount: {
        display: 'inline-block',
        width: '56px',
        height: '56px',
        lineHeight: '56px',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        color: 'white',
        borderRadius: '50%',
        fontSize: '24px',
        fontWeight: '700',
    },
    plusIcon: {
        display: 'inline-block',
        width: '56px',
        height: '56px',
        lineHeight: '56px',
        background: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
        color: 'white',
        borderRadius: '50%',
        fontSize: '32px',
        fontWeight: '600',
    },
    menuCardTitle: {
        fontSize: '20px',
        fontWeight: '600',
        color: '#333',
        marginBottom: '8px',
    },
    menuCardDesc: {
        fontSize: '14px',
        color: '#666',
    },
    reviewContainer: {
        maxWidth: '700px',
        margin: '0 auto',
    },
    reviewProgress: {
        height: '6px',
        background: '#e8e8e8',
        borderRadius: '3px',
        marginBottom: '32px',
        overflow: 'hidden',
    },
    reviewProgressFill: {
        height: '100%',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        borderRadius: '3px',
        transition: 'width 0.3s ease',
    },
    flashcard: {
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        minHeight: '280px',
        borderRadius: '20px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
        marginBottom: '24px',
        boxShadow: '0 8px 32px rgba(102, 126, 234, 0.3)',
        transition: 'all 0.3s ease',
        position: 'relative',
    },
    flashcardFlipped: {
        background: 'white',
        border: '3px solid #667eea',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.1)',
    },
    flashcardContent: {
        fontSize: '28px',
        fontWeight: '600',
        color: 'white',
        padding: '40px',
        textAlign: 'center',
    },
    flashcardContentBack: {
        fontSize: '28px',
        fontWeight: '600',
        color: '#667eea',
        padding: '40px',
        textAlign: 'center',
    },
    flipHint: {
        position: 'absolute',
        bottom: '20px',
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: '14px',
    },
    reviewButtonsContainer: {
        background: 'white',
        borderRadius: '16px',
        padding: '24px',
        boxShadow: '0 4px 20px rgba(0, 0, 0, 0.06)',
    },
    reviewPrompt: {
        textAlign: 'center',
        color: '#666',
        marginBottom: '20px',
        fontSize: '16px',
    },
    reviewButtons: {
        display: 'grid',
        gridTemplateColumns: 'repeat(4, 1fr)',
        gap: '12px',
    },
    reviewButton: {
        padding: '16px 12px',
        borderRadius: '12px',
        border: 'none',
        color: 'white',
        cursor: 'pointer',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '4px',
        transition: 'transform 0.2s ease',
    },
    reviewAgain: {
        background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    },
    reviewHard: {
        background: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
    },
    reviewGood: {
        background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    },
    reviewEasy: {
        background: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
    },
    reviewButtonLabel: {
        fontSize: '16px',
        fontWeight: '600',
    },
    reviewButtonDesc: {
        fontSize: '11px',
        opacity: 0.9,
    },
    flashcardGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
        gap: '20px',
        marginTop: '20px',
    },
    flashcardItem: {
        background: 'white',
        borderRadius: '16px',
        padding: '24px',
        boxShadow: '0 4px 16px rgba(0, 0, 0, 0.06)',
    },
    flashcardDue: {
        borderLeft: '4px solid #f5576c',
    },
    flashcardItemHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: '8px',
    },
    flashcardFront: {
        fontSize: '18px',
        fontWeight: '600',
        color: '#333',
    },
    dueBadge: {
        fontSize: '12px',
        padding: '4px 10px',
        background: '#fff0f0',
        color: '#f5576c',
        borderRadius: '4px',
        fontWeight: '600',
    },
    flashcardBack: {
        fontSize: '16px',
        color: '#667eea',
        fontWeight: '500',
        marginBottom: '16px',
    },
    flashcardMeta: {
        display: 'flex',
        gap: '16px',
        fontSize: '13px',
        color: '#999',
        marginBottom: '8px',
        flexWrap: 'wrap',
    },
    flashcardNextReview: {
        fontSize: '13px',
        color: '#666',
        marginBottom: '12px',
    },
    formGroup: {
        marginBottom: '20px',
    },
    formLabel: {
        display: 'block',
        fontSize: '14px',
        fontWeight: '600',
        color: '#333',
        marginBottom: '8px',
    },

    // Login styles
    loginContainer: {
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '20px',
    },
    loginCard: {
        background: 'white',
        borderRadius: '24px',
        padding: '40px',
        width: '100%',
        maxWidth: '420px',
        boxShadow: '0 20px 60px rgba(0, 0, 0, 0.2)',
        animation: 'fadeIn 0.6s ease',
    },
    loginTitle: {
        textAlign: 'center',
        marginBottom: '30px',
        fontSize: '28px',
        fontWeight: '800',
        color: '#333',
    },
    switchText: {
        textAlign: 'center',
        marginTop: '20px',
        color: '#666',
    },
    switchLink: {
        color: '#667eea',
        fontWeight: '600',
        cursor: 'pointer',
    },
    fileInputWrapper: {
        marginBottom: '14px',
    },
    fileSelectButton: {
        width: '100%',
        padding: '14px 20px',
        border: '2px dashed #667eea',
        borderRadius: '10px',
        fontSize: '14px',
        fontWeight: '500',
        cursor: 'pointer',
        background: 'rgba(102, 126, 234, 0.05)',
        color: '#667eea',
        textAlign: 'center',
        transition: 'all 0.2s ease',
    },
    selectedFileName: {
        display: 'block',
        marginTop: '8px',
        fontSize: '13px',
        color: '#667eea',
        fontWeight: '500',
    },
};
